/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-08-13 17:26:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* General styles */\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    background-color: #f2f2f2;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Container for all boxes */\r\n");
      out.write(".box {\r\n");
      out.write("    width: 22%;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    margin: 1%;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: transform 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box:hover {\r\n");
      out.write("    transform: scale(1.03);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Title inside each box */\r\n");
      out.write(".box-content h2 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Image inside each box */\r\n");
      out.write(".box-image {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 180px;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Paragraph inside each box */\r\n");
      out.write(".box-content p {\r\n");
      out.write("    color: #0073e6;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Container fix */\r\n");
      out.write(".clearfix::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    clear: both;\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>Heloo</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box1 box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Electronics</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('images/box1.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Beauty Products</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box2.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Mobile Accesories</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box3.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Educational</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box4.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Clothes</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box5.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Wathes</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box6.jpg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Bags</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box7.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <h2>Kitchen Accesories</h2>\r\n");
      out.write("                <div class=\"box-image\" style=\"background-image: url('box8.jpeg');\"></div>\r\n");
      out.write("                <p>See More</p>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
