/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-04-11 09:58:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.internal.build.AllowSysOut;
import com.ecomm.entity.Product;
import com.ecomm.dao.ProductDao;
import com.ecomm.entity.User;
import com.ecomm.dao.UserDao;

public final class productDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.ecomm.dao.ProductDao");
    _jspx_imports_classes.add("com.ecomm.entity.User");
    _jspx_imports_classes.add("com.ecomm.entity.Product");
    _jspx_imports_classes.add("com.ecomm.dao.UserDao");
    _jspx_imports_classes.add("org.hibernate.internal.build.AllowSysOut");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Product Details</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".hero-section {\r\n");
      out.write("	background-image: url(\"img/hero.jpg\");\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        background: linear-gradient(to right, #f8f9fa, #e9ecef);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-details {\r\n");
      out.write("        max-width: 1000px;\r\n");
      out.write("        margin: 50px auto;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-header {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        gap: 40px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-header img {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-info h1 {\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        color: #343a40;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-info p {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .add-to-cart {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        background-color: #28a745;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 12px 25px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .add-to-cart:hover {\r\n");
      out.write("        background-color: #218838;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("		<h1>AP Mart</h1>\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul>\r\n");
      out.write("			<li><a href=\"Register.jsp\">Register</a></li>\r\n");
      out.write("			<li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("				<li><a href=\"Product.jsp\">Products</a></li>\r\n");
      out.write("				<li><a href=\"viewcart.jsp\">Cart</a></li>\r\n");
      out.write("				<li><a href=\"index.jsp\">LogOut</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"hero-section\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");

	int id=Integer.parseInt(request.getParameter("pid"));
	Product p=ProductDao.getProductById(id);

	User user=(User) session.getAttribute("user");
	session.setAttribute("user",user);
	System.out.println("pd.jsp"+user);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"product-details\">\r\n");
      out.write("	<div class=\"product-header\">\r\n");
      out.write("		<img src=\"");
      out.print(p.getImage_url() );
      out.write("\" alt=\"Product Image\">\r\n");
      out.write("		<div class=\"product-info\">\r\n");
      out.write("			<h1>");
      out.print(p.getName() );
      out.write("</h1>\r\n");
      out.write("			<p>");
      out.print(p.getDescription() );
      out.write("</p>\r\n");
      out.write("			<a href=\"addToCart.jsp?pid=");
      out.print(p.getId() );
      out.write("\">\r\n");
      out.write("			<button class=\"add-to-cart\">Add To Cart</button></a>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
